"""Initial migration.

Revision ID: 10d6a605cf19
Revises: 
Create Date: 2024-07-10 02:10:16.033557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d6a605cf19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_docker_build', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_registry_publish', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registry_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_docker_build', schema=None) as batch_op:
        batch_op.drop_column('registry_info')
        batch_op.drop_column('is_registry_publish')

    # ### end Alembic commands ###
