"""Automatic migration

Revision ID: e210227830e3
Revises: 4e327b54e37e
Create Date: 2024-07-13 01:29:15.498233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e210227830e3'
down_revision = '4e327b54e37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
