name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Pipenv
      run: python3 -m pip install pipenv
    
    - name: Build backend
      working-directory: ./backend
      run: |
        pipenv install
        pipenv run python ./pyinstaller-build.py
    
    - name: Install dependencies
      run: pnpm install --force
    
    - name: Build Electron App for ${{ matrix.os }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
          pnpm run build:linux
        elif [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
          pnpm run build:mac
        elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
          pnpm run build:win
        fi

    - name: Display contents of dist directory
      run: |
        ls -la ./dist

    - name: Display contents of dist resources
      run: |
        ls -la ./resources

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: dist/dockman-1.0.0-arm64.dmg
        asset_name: dockman-1.0.0-arm64.dmg
        tag: ${{ github.ref }}


